### ISSUE TITLE
Join message delay

### ISSUE THREAD

**Issue by MinecraftAdmin** [minecrafter/SuperbVote#143]
Hello! Please can you add a join-delay to the vote-reminder message? This is so it can be programmed to show up after the main server MOTD
```YML
vote-reminder:
  message: "&d[Vote] &fDont forget to vote for the server to get &d5 vote crate keys&f and &d$1250&f! Keys can be used at &d/warp crates&f! &d/ᴠᴏᴛᴇ &d"
  on-join: true
  on-join-delay: 500 #Milliseconds
  repeat: 600 #Seconds
```
