### ISSUE TITLE
player-message not working

### ISSUE THREAD

**Issue by Alv5ro** [minecrafter/SuperbVote#96]
The "player-message" doesn't output the message to the player. There's no broadcast message, I'm not sure if I'm meant to have one for the player-message to work, I'm guessing not. I don't understand why this is happening, I've checked that it's valid yaml, which it is. Here's the part of the config, please let me know if you want the whole config, thanks!
```
rewards:
  # Example of matchers. See https://github.com/minecrafter/SuperbVote/wiki/Configuration#if for a full list of available
  # matchers.
  - if:
      permission: superbvote.10k
      chance-percentage: 50
      #service: SpecialService
    commands:
    - eco give %player% 10000
    player-message: "&aThanks for voting, you have been rewarded with $10,000."
    #broadcast-message: "&a%player% got really lucky and was rewarded with $10000!"
  # A default reward is required. Default rewards are defined by using default: true as a matcher. No other matchers can
  # be used with this matcher and only one such reward can be the default reward.
  - if:
      permission: superbvote.10k
      chance-percentage: 30
    commands:
    - eco give %player% 20000
    player-message: "&aThanks for voting, you have been rewarded with $20,000."
    #broadcast-message: "&a%player% got really lucky and was rewarded with $10000!"
  # A default reward is required. Default rewards are defined by using default: true as a matcher. No other matchers can
  # be used with this matcher and only one such reward can be the default reward.
  - if:
      permission: superbvote.10k
      chance-percentage: 20
    commands:
    - cc give physical vote 1 %player%
    broadcast-message: "&5&l%player% &7voted and recieved a &8[&c»&8]&a&lVOTE&8[&c«&8] &b&lKey"
    player-message: "&7Go to /warp crates to redeem"
  - if:
      default: true
    commands:
    - eco give %player% 10000
    player-message: "&aThanks for voting, you have been rewarded with $10,000."
```
